codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        informational: true
      root:
        flags:
          - root
        informational: true
      backend:
        flags:
          - backend
        target: 85%
        threshold: 2%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "**/*.spec.ts"
  - "**/*.e2e-spec.ts"
