apiVersion: v1
kind: Service
metadata:
  name: cthutool-backend
  namespace: cthutool
  labels:
    app.kubernetes.io/name: cthutool-backend
    app.kubernetes.io/part-of: cthutool
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: cthutool-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
