import { copyFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import builtins from 'builtin-modules';
import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const args = new Set(process.argv.slice(2));
const outdirArg = process.argv.find((value) => value.startsWith('--outdir='));
const explicitOutdir = outdirArg ? outdirArg.slice('--outdir='.length) : undefined;
const outdir = explicitOutdir || process.env.OBSIDIAN_PLUGIN_DIR || 'dist';
const absOutdir = path.resolve(process.cwd(), outdir);

const isProduction = args.has('--production');
const isWatch = args.has('--watch');

const syncPluginAssets = {
  name: 'sync-plugin-assets',
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) {
        return;
      }

      await mkdir(absOutdir, { recursive: true });
      await Promise.all([
        copyFile(path.resolve('manifest.json'), path.join(absOutdir, 'manifest.json')),
        copyFile(path.resolve('styles.css'), path.join(absOutdir, 'styles.css')),
        copyFile(path.resolve('versions.json'), path.join(absOutdir, 'versions.json'))
      ]);
    });
  }
};

const ctx = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es2018',
  sourcemap: isProduction ? false : 'inline',
  minify: isProduction,
  treeShaking: true,
  logLevel: 'info',
  outfile: path.join(absOutdir, 'main.js'),
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins
  ],
  plugins: [syncPluginAssets]
});

if (isWatch) {
  await ctx.watch();
  console.log(`[obsidian-enhancer] watching -> ${absOutdir}`);
} else {
  await ctx.rebuild();
  await ctx.dispose();
}
