apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cthutool
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mickmetalholic/CthuTool
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: cthutool
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
