import { spawn } from 'node:child_process';
import { mkdtemp, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, join } from 'node:path';
import type { Converter, ConvertResult } from '../../domain/converter';
import { conversionFailure } from '../../domain/errors';
import { toArchiveName } from '../../domain/path-mapping';

const runCommand = (
  bin: string,
  args: ReadonlyArray<string>,
): Promise<{
  readonly code: number;
  readonly stdout: string;
  readonly stderr: string;
}> =>
  new Promise((resolve, reject) => {
    const child = spawn(bin, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => {
      stdout += String(d);
    });
    child.stderr.on('data', (d) => {
      stderr += String(d);
    });
    child.on('error', reject);
    child.on('close', (code) => resolve({ code: code ?? 1, stdout, stderr }));
  });

const parsePdfPageCount = (content: string): number => {
  const line = content
    .split(/\r?\n/)
    .find((x) => x.toLowerCase().startsWith('pages:'));
  if (!line) return 0;
  const match = line.match(/Pages:\s*(\d+)/i);
  return match ? Number(match[1]) : 0;
};

export const pdfConverter: Converter = {
  sourceType: 'pdf',
  async convert(file, ctx): Promise<ConvertResult> {
    const root = await mkdtemp(join(tmpdir(), 'cthu-pdf-pages-'));
    const imageExt = ctx.options.imageFormat;
    const prefix = join(
      root,
      basename(file.sourcePath).replace(/\.[^.]+$/, ''),
    );

    const info = await runCommand('pdfinfo', [file.sourcePath]);
    if (info.code !== 0) {
      return {
        ok: false,
        failure: conversionFailure(
          file.sourcePath,
          'convert',
          info.stderr.trim() || 'pdfinfo failed',
        ),
      };
    }
    const total = Math.max(1, parsePdfPageCount(info.stdout));
    ctx.onProgress?.(file, { current: 0, total, message: 'pdfinfo ready' });

    const fmtArg = imageExt === 'jpg' ? '-jpeg' : `-${imageExt}`;
    const convert = await runCommand('pdftoppm', [
      fmtArg,
      '-r',
      String(ctx.options.dpi),
      file.sourcePath,
      prefix,
    ]);
    if (convert.code !== 0) {
      return {
        ok: false,
        failure: conversionFailure(
          file.sourcePath,
          'convert',
          convert.stderr.trim() || 'pdftoppm failed',
        ),
      };
    }

    const ext = imageExt === 'jpg' ? 'jpg' : imageExt;
    const generated = (await readdir(root))
      .filter((x) => x.toLowerCase().endsWith(`.${ext}`))
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

    if (generated.length === 0) {
      return {
        ok: false,
        failure: conversionFailure(
          file.sourcePath,
          'convert',
          'No pages generated by pdftoppm',
        ),
      };
    }

    ctx.onProgress?.(file, {
      current: generated.length,
      total,
      message: 'processed',
    });
    return {
      ok: true,
      pages: generated.map((name, idx) => ({
        index: idx + 1,
        tempPath: join(root, name),
        archiveName: toArchiveName(idx + 1, ext),
        format: imageExt,
        quality: ctx.options.imageQuality,
      })),
    };
  },
};
